### ISSUE TITLE
NameError: name 'print_cost' is not defined

### ISSUE THREAD

**Issue by sara-kassani** [manideep2510/melanoma_segmentation#1]
I was trying to run your code and I've got this name error. Would you please give some information about how to fix it?

<ipython-input-14-5ca899320701> in model(X_train, Y_train, X_test, Y_test, learning_rate, num_epochs, minibatch_size, reuse)
     54 
     55                 # Print the cost every epoch
---> 56                 if print_cost == True and epoch % 5 == 0:
     57                     print ("Cost after epoch %i: %f" % (epoch, minibatch_cost))
     58                 if print_cost == True and epoch % 1 == 0:

NameError: name 'print_cost' is not defined

**Comment by manideep2510** [comment]
Sorry for the late reply, I have updated the code. The error was because should be  a "print_cost = True" argument in the function, model(X_train, Y_train, X_test, Y_test, learning_rate, num_epochs, minibatch_size, reuse) i.e, 
it should be model(X_train, Y_train, X_test, Y_test, learning_rate, num_epochs, minibatch_size, reuse, **print_cost = True**)
